apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-09-13T13:11:19Z
  labels:
    kops.k8s.io/cluster: clothgram.k8s.local
  name: spot-ig
spec:
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: t2.micro
  maxPrice: "0.0040"
  maxSize: 3
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: spot-ig
    on-demand: "false"
  role: Node
  subnets:
  - ap-south-1a
  - ap-south-1b
