apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: clothgram.k8s.local
  name: spot-ig
spec:
  cloudLabels:
    Role: compute
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: t2.micro
  role: Node
  maxSize: 4
  rootVolumeSize: 30
  minSize: 1
  # You can manually set the maxPrice you're willing to pay - it will default to the onDemand price.
  maxPrice: ".0068"
  # add the mixed instance policy here
  mixedInstancesPolicy:
    instances:
    - t3.small
    - t2.small
    - t2.medium
    onDemandAboveBase: 0
    spotInstancePools: 3
  subnets:
  - ap-south-1a
  - ap-south-1b
