kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dev-storage
  namespace: development
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi