apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  namespace: production
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
    - host: ne.kube.rukjaana.com
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: ne-frontend-cluster-ip-service
              servicePort: 3000
    - host: www.ne.kube.rukjaana.com
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: ne-frontend-cluster-ip-service
              servicePort: 3000
    - host: nedevelopers.in
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: ne-frontend-cluster-ip-service
              servicePort: 3000
    - host: www.nedevelopers.in
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: ne-frontend-cluster-ip-service
              servicePort: 3000
