apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: development
spec:
  replicas: 1 # This what we are making extra changes compare to kind pod and adding matchlevels 
  selector:
    matchLabels:
      component: web # This label give access to templates:metadata:labels 
  template:
    metadata:
      labels:
        component: web # This lable is used by match Labels
    spec:
      containers:
        - name: client
          image: stephengrider/multi-client
          ports:
           - containerPort: 3000
