apiVersion: v1
kind: Service
metadata:
  name: event-api-cluster-ip-service
  namespace: development
spec:
  type: ClusterIP
  selector:
    component: event-api-server
  ports:
    - port: 8080 #this port will be available internally 
      targetPort: 8080 #this port of web 
