apiVersion: v1
kind: Service
metadata:
  name: event-web-cluster-ip-service
  namespace: development
spec:
  type: ClusterIP
  selector:
    component: event-web-clothgram
  ports:
    - port: 4000 #this port will be available internally 
      targetPort: 4000 #this port of web 