apiVersion: v1
kind: PersistentVolume
metadata:
  name: vue-api
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: vue-api
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0377f8d2

---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vue-api
provisioner: efs.csi.aws.com