apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ne-autoscaler
  namespace: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ne-clothgram-frontend
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50