apiVersion: v1
kind: Service
metadata:
  name: jenkins-api-services
  namespace: development
spec:
  type: ClusterIP
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      targetPort: 50000
      port: 50000