apiVersion: v1
kind: Service
metadata:
  name: jenkins-web-services
  namespace: development
spec:
  type: ClusterIP
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 8080