#Cluster IP will available to kubernetes internal conncectivty 

apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-services
  namespace: development
spec:
  type: ClusterIP
  selector:
    component: web
  ports:
    - port: 3000 #this port will be available internally 
      targetPort: 3000 #this port of web 
