apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: development
spec:
  replicas: 0
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: niteshldd/multi-client
          ports:
            - containerPort: 3000