apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  namespace: development
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: dev.kube.rukjaana.com
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: client-cluster-ip-services
              servicePort: 3000
          - path: /api/?(.*)
            backend:
              serviceName: server-cluster-ip-services
              servicePort: 5000
    - host: www.dev.kube.rukjaana.com
      http:
        paths:
          - path: /
            backend:
              serviceName: client-cluster-ip-services
              servicePort: 3000
          - path: /api
            backend:
              serviceName: server-cluster-ip-services
              servicePort: 5000  
    - host: jenkins.kube.rukjaana.com
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: jenkins-web-services
              servicePort: 8080
          - path: /api/?(.*)
            backend:
              serviceName: jenkins-api-services
              servicePort: 50000
    - host: clothgram.kube.rukjaana.com
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: clothgram-frontend-cluster-ip-services
              servicePort: 80

    - host: dash-clothgram.kube.rukjaana.com
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: clothgram-dashboard-cluster-ip-services
              servicePort: 90

    - host: api-clothgram.kube.rukjaana.com
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: clothgram-server-cluster-ip-service
              servicePort: 8000
          # - path: /api/?(.*)
          #   backend:
          #     serviceName: jenkins-api-services
          #     servicePort: 50000

  