apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  namespace: development
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: dev.kube.rukjaana.com
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: client-cluster-ip-services
              servicePort: 3000
          - path: /api/?(.*)
            backend:
              serviceName: server-cluster-ip-services
              servicePort: 5000
    - host: www.dev.kube.rukjaana.com
      http:
        paths:
          - path: /
            backend:
              serviceName: client-cluster-ip-services
              servicePort: 3000
          - path: /api
            backend:
              serviceName: server-cluster-ip-services
              servicePort: 5000  

  