apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  namespace: development
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # kubernetes.io/ingress.class: alb
    # alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    # alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
spec:
  rules:
    - host: dev.kube.rukjaana.com
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: client-cluster-ip-services
              servicePort: 3000
          - path: /api/?(.*)
            backend:
              serviceName: server-cluster-ip-services
              servicePort: 5000
    - host: www.dev.kube.rukjaana.com
      http:
        paths:
          - path: /
            backend:
              serviceName: client-cluster-ip-services
              servicePort: 3000
          - path: /api
            backend:
              serviceName: server-cluster-ip-services
              servicePort: 5000  
    - host: jenkins.kube.rukjaana.com
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: jenkins-web-services
              servicePort: 8080
          - path: /api/?(.*)
            backend:
              serviceName: jenkins-api-services
              servicePort: 50000

  ####CLOTHGRAM DOMAIN#######
    - host: clothgram.kube.rukjaana.com
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: clothgram-frontend-cluster-ip-services
              servicePort: 80
    - host: clothgram.co
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: clothgram-frontend-cluster-ip-services
              servicePort: 80
    - host: www.clothgram.co
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: clothgram-frontend-cluster-ip-services
              servicePort: 80

    - host: dash-clothgram.kube.rukjaana.com
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: clothgram-dashboard-cluster-ip-services
              servicePort: 90

    - host: api-clothgram.kube.rukjaana.com
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: clothgram-server-cluster-ip-service
              servicePort: 8000
          # - path: /api/?(.*)
          #   backend:
          #     serviceName: jenkins-api-services
          #     servicePort: 50000

    - host: test-dash-cloth.kube.rukjaana.com
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: clothgram-dashboard-cluster-ip-services-test
              servicePort: 90
    - host: test-clothgram.kube.rukjaana.com
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: clothgram-frontend-cluster-ip-services-test
              servicePort: 80
###### CLOTHGRAM DOMAIN END #######

#### TICKET DOMAIN START###########
    - host: ticket.kube.rukjaana.com
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: ssl-redirect
              serviceName: rukjaana-ticket-server-cluster-ip-service
              servicePort: 8118
    - host: www.ticket.kube.rukjaana.com
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: ssl-redirect
              serviceName: rukjaana-ticket-server-cluster-ip-service
              servicePort: 8118
    - host: ticket.uruvelaa.com
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: ssl-redirect
              serviceName: rukjaana-ticket-server-cluster-ip-service
              servicePort: 8118
####### TICKET DOMAIN END ###########


    - host: event.clothgram.co
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: ssl-redirect
              serviceName: event-web-cluster-ip-service
              servicePort: 4000
    - host: event.kube.rukjaana.com
      http:
        paths:
          - path: /api/?(.*)
            backend:
              serviceName: ssl-redirect
              serviceName: event-api-cluster-ip-service
              servicePort: 8080
    - host: event.clothgram.co
      http:
        paths:
          - path: /api/?(.*)
            backend:
              serviceName: ssl-redirect
              serviceName: event-api-cluster-ip-service
              servicePort: 8080














              