apiVersion: v1
kind: Service
metadata:
  name: postrgess-cluster-ip-services
  namespace: development
spec:
  type: ClusterIP
  selector:
    newlabels: postgress
  ports:
    - targetPort: 5432
      port: 5432

