apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-ip-services
  namespace: development
spec:
  type: ClusterIP
  selector:
      newlabels: redis
  ports:
    - targetPort: 6379
      port: 6379