apiVersion: v1
kind: Service 
metadata:
  name: server-cluster-ip-services
  namespace: development
spec:
  type: ClusterIP
  selector:
    newlabels: server
  ports:
    - port: 5000
      targetPort: 5000
      
    