apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    component: grafana
  ports:
    - port: 3000 #this port will be available internally 
      targetPort: 3000 #this port of web 
      protocol: TCP
