apiVersion: v1
kind: Service
metadata:
  name: telegraf
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    component: telegraf
  ports:
    - port: 8125 #this port will be available internally 
      targetPort: 8125 #this port of web 
      protocol: UDP
