apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: development
spec:
  replicas: 2 # This what we are making extra changes compare to kind pod and adding matchlevels 
  selector:
    matchLabels:
      component: web # This label give access to templates:metadata:labels 
  template:
    metadata:
      labels:x
        component: web # This lable is used by match Labels
    spec:
      containers:
        - name: client
          image: niteshldd/multi-client
          ports:
           - containerPort: 3000 #changing configuration in client-deployment will applied by changing the configuration

#Deplyoment will roll the new configuration 