apiVersion: apps/v1
kind: Deployment
metadata:
  name: clothgram-server
  namespace: development
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      newlabels: clothgram-server
  template:
    metadata:
      labels:
        newlabels: clothgram-server
    spec:
      containers:
        - name: clothgram-server
          image: niteshldd/clothgram:latest
          # command: ["python3 manage.py migrate --no-input && python3 manage.py collectstatic --noinput && python3 manage.py populatedb --createsuperuser"]
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgres://postgres:pg12345nitesh@postrgess-cluster-ip-services/postgres
            - name: CELERY_BROKER_URL
              value: redis://redis-cluster-ip-services:6379/1
            - name: SECRET_KEY
              value: 'niteshkwhdiw'
            - name: JWT_VERIFY_EXPIRATION
              value: 'True'
            - name: ALLOWED_HOSTS
              value: '*'

        # - name: saleor-storefront
        #   image: niteshldd/saleor-storefront:latest
        #   env: 
        #     - name: "clothgram-server"
        #       value: "localhost:8000"
        #   ports:
        #     - containerPort: 80
        # - name: dashoboard-storefront
        #   image: niteshldd/saleor-dashboard:latest
        #   env: 
        #     - name: "clothgram-server"
        #       value: "localhost:8000"
        #   ports:
        #     - containerPort: 90

